//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetMVCWorkShop1_V3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_BookEntities2 : DbContext
    {
        public db_BookEntities2()
            : base("name=db_BookEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book_Class> Book_Class { get; set; }
        public virtual DbSet<Book_Code> Book_Code { get; set; }
        public virtual DbSet<Book_Data> Book_Data { get; set; }
        public virtual DbSet<ER> ER { get; set; }
        public virtual DbSet<Member_M> Member_M { get; set; }
    }
}
